name: Build & Release

on:
  push:
    tags: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.1.0
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Save to CHANGELOG
        run: echo "${{ steps.changelog.outputs.changelog }}" > CHANGELOG.md

      - name: Set up JDK 17
        uses: actions/setup-java@v3.12.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: "BloCommands"
          path: |
            ./target/BloCommands*.jar
            CHANGELOG.md

      - name: GH Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.changelog.outputs.changelog }}
          fail_on_unmatched_files: true
          files: "./target/BloCommands*.jar"
          draft: false
          prerelease: false